on:
  push:
    branches:
      - master
name: Deploy lambdas

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Build raw data loader lambda
        run: |
          cd raw_data_loader \
          mkdir package \
          pip install --target ./package -r requirements.txt \
          cd package \
          zip -r ../raw_data_loader.zip . \
          cd .. \
          zip raw_data_loader.zip card_fetcher.py

      - name: Deploy raw data loader
        run: aws lambda update-function-code --function-name extract-raw-data --zip-file raw_data_loader/raw_data_loader.zip